### ISSUE TITLE
Icon buttons all have the same id

### ISSUE THREAD

**Issue by EmilyYond** [material-components/material-web#5213] opened 2023-11-22 10:21 UTC
### What is affected?

Component

### Description

![Screenshot 2023-11-22 at 10 17 30](https://github.com/material-components/material-web/assets/128067060/baa820b0-8283-4376-905f-17acbf88e25f)

### Reproduction

When using <md-icon-button> filled or standard, google flags a warning that they all have the same id. Can this just be removed? They don't need to have an id at all.

### Workaround

Tried to add my own id's to override, but unable to. No work around available.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

"@material/web": "^1.0.1",

### Browser/OS/Node environment

Browser: Chrome 119
Node: v18.16.1
Stack: Nuxt 3.8.0

**Comment by asyncLiz** [comment] 2023-11-22 16:29
I believe this is working as intended. IDs are scoped to the nearest document or shadow root, so the IDs are unique within the component's shadow dom.

Are you using any tooling to remove the shadow dom?

**Comment by asyncLiz** [comment] 2023-12-04 22:32
Closing since this is working as intended

**Closed by asyncLiz** 2023-12-04 22:32 UTC
