### ISSUE TITLE
Why does md-select have min-width: 210px ?

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4376] opened 2023-05-31 20:16 UTC
I have a select that should only be around 40 width, but it's being forced to 210 with this:

https://github.com/material-components/material-web/blob/9aa90a87cfe2dbd99a48e7ee268fb935db6b75a1/select/lib/_shared.scss#L20

Any reason why or can that be reduced/removed?

**Comment by e111077** [comment] 2023-06-01 18:44
This is to match the default min width of md-textfield components since md-select doesn't actually have an `<input>` in its shadow DOM but rather an empty span, its default width is simply the built-in padding and look like this:

<img width="69" alt="image" src="https://github.com/material-components/material-web/assets/5981958/23f72ec7-9c50-45af-9ae8-2cf00f12fd7f">


You can remove this min-width with:

```css
md-outlined-select, md-filled-select {
  min-width: unset;
}
```

Here's a reproduction:

https://lit.dev/playground/#gist=39caf419e77e5ff20525e9f4ad03b8d3

Closing this as WAI. If you still have issues with this, or think the default behavior should change, please comment and I'll reopen

**Closed by e111077** 2023-06-01 18:44 UTC
