### ISSUE TITLE
Icon documentation

### ISSUE THREAD

**Issue by MarkStega** [material-components/material-web#5259] opened 2023-12-05 18:31 UTC
### Description

For some reason 'Icon' is missing from the roadmap showing "Material 1.0 | Sep 2023" features and components.

I do see that documentation now exists for icon in the source but it is not reflected in the "https://material-web.dev/" menu

The documentation says that two axes (optical size and weight) are handled automatically but does not describe the mechanism in how those axes are determined.

### Browser/OS Environment

Not pertinent to this issue.

**Comment by asyncLiz** [comment] 2023-12-05 19:25
Duplicate of https://github.com/material-components/material-web/issues/5206

https://fonts.google.com/icons is a good resource to learn a bit more about the axes. We recommend those two axes be managed with `font-weight` and `font-size` to reduce the payload size of importing the icons.

**Closed by asyncLiz** 2023-12-05 19:26 UTC
