### ISSUE TITLE
[md-filled-button] TypeError: currentDirective._$initialize is not a function

### ISSUE THREAD

**Issue by CollinHerber** [material-components/material-web#4101] opened 2023-03-29 01:13 UTC
```
lit-html.js:648 Uncaught (in promise) TypeError: currentDirective._$initialize is not a function
    at resolveDirective (lit-html.js:648:1)
    at AttributePart._$setValue (lit-html.js:1172:1)
    at TemplateInstance._update (lit-html.js:730:1)
    at ChildPart._commitTemplateResult (lit-html.js:998:1)
    at ChildPart._$setValue (lit-html.js:847:1)
    at render (lit-html.js:1459:1)
    at MdFilledButton.update (lit-element.js:6:1)
    at MdFilledButton.performUpdate (reactive-element.js:818:1)
    at MdFilledButton.scheduleUpdate (reactive-element.js:753:1)
    at MdFilledButton.__enqueueUpdate (reactive-element.js:726:1)
```

The following is displayed in chrome console and the button does not load. This was working prior to today so a little confused what could be causing it.

Using Webpack 5,.76.3 in local development.

`<md-filled-button label="Label"></md-filled-button>`

**Comment by asyncLiz** [comment] 2023-04-25 17:18
Closing for now, please reopen with a repro if this is still an issue!

**Closed by asyncLiz** 2023-04-25 17:18 UTC

**Comment by didnotwant** [comment] 2023-08-09 07:46
Hi @CollinHerber –  I've experienced this (very rare – after googling it) problem not exactly in the material components, but while using a 3rd party Lit component on an Astro page, where I also had Lit (Astro uses an integration of Lit's).

In my case, this error was caused by having the Astro's Lit in dev mode, while the Lit in the 3rd party component was "prod" (minified).

So you may check if you have multiple Lit instances on your page, and if they're in different modes.

You may also check if your multiple Lit versions are the same, but for me the problem gone once I had the environment-compatible Lit instances.

**Comment by enkelmedia** [comment] 2024-04-03 00:07
I wanted to add to this as well, I was using a Lit version that was exported from a external library (prod-version) and got this error, changed to a "local" version which worked again. 

Both were the same Lit-version.
