### ISSUE TITLE
How to prevent icon names from showing (or anything for that matter) until component loads

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4162] opened 2023-04-17 21:18 UTC
Since icon and icon-button are using slots, the user will see the icon/symbol name for a bit until the component loads, then it replaces it with the icon. What's the best practice for preventing that?

Seems like the component should prevent this since there's probably no use case where it would make sense to show the icon name before the component loads.

**Comment by e111077** [comment] 2023-04-18 01:12
This is something we will have to look into a bit more. Next release includes a change where overflow is hidden so it should limit the effect if the bottleneck is loading the font and not the definition.

If the issue is with the definition, you can select undefined elements in CSS with:

```css
md-icon:not(:defined) {
  /* Hide visibility */
}
```

**Comment by treeder** [comment] 2023-04-18 22:04
For what it's worth, the `mwc-icon-button` had an `icon` attribute which avoided this problem.

**Comment by e111077** [comment] 2023-04-19 20:53
@treeder the reason behind the slot is that we didn't want to forcibly package md-icon into components as users sometimes go full SVG / img and never even use md-icon

@asyncLiz WDYT of adding an `icon` attribute to `<md-icon>` that just renders as slot content?

**Comment by asyncLiz** [comment] 2023-05-08 17:00
(would LOVE a community PR to add this ❤️)

**Comment by AndrewJakubowicz** [comment] 2023-07-14 14:56
Just to clarify my understanding of this issue, do we want to deprecate/remove using a slot (pre-1.0)? Currently we support both `<md-icon><svg>...</svg></md-icon>` or `<md-icon>search</md-icon>`.  Instead, we want `md-icon` to be focussed on just the font icon case, with a revised public API using an `icon` attribute: `<md-icon icon="search"></md-icon>`? Should the slot case continue to work or be removed?

Is my assumption correct that migration for anyone wrapping svgs (or other icons) with `md-icon` will be to unwrap the svg or icon?

**Comment by treeder** [comment] 2023-07-14 15:19
I'm actually not sure this is still an issue, I haven't noticed the text showing up then switching to an icon with the latest releases so maybe this is already resolved?

**Comment by asyncLiz** [comment] 2023-07-14 19:43
> Just to clarify my understanding of this issue, do we want to deprecate/remove using a slot (pre-1.0)? Currently we support both `<md-icon><svg>...</svg></md-icon>` and `<md-icon>search</md-icon>`. Instead, do we want `md-icon` to be focussed on just the font icon case, with a revised public API using an `icon` attribute: `<md-icon icon="search"></md-icon>`. Or is this an addition to `md-icon`? Thank you!

I think we should deprecate slotting the text and use only the icon attribute as the best practice.

**Comment by asyncLiz** [comment] 2023-07-14 19:43
Md-icon should only be focused on font icons, yea. Svgs should not be wrapped in it

**Comment by e111077** [comment] 2023-07-28 21:34
After further discussion on the team, this issue is something that should be fixed at the application level or the fonts level. There is not much we can do at the component level unless the web platform gives us more font loading notification features.

Slots vs attributes don't seem to be the problem as [in this example](https://lit.dev/playground/#gist=ed7d8e280ff4d30c6b07042c59cfdf4d), if you open it in a new tab and throttle your network speed to be super slow, you'll see that the element definitions load before material symbols library. It's not about the definition load, it's all about the font load.

## Possible app workarounds:

The underlying issue is that Material Symbols Outlined is a massive file.

### Decrease the size of icon font

Codepoints may still render as a square in some browsers, but this allows you to form a google fonts URL that loads only the icons you need making this generally a non-issue on slow connections.

To help with DX, [we have made a crude tool](https://lit.dev/playground/#gist=0fb96617939dbdb4214ec3ac549ffb06&view-mode=preview) to help generate the URL and the markup necessary. We have also been in contact with the google fonts team to provide an officially-supported tool or workflow to support this use case.

### Display md-icons once font is loaded

On most connections you can just add `&display=block` to the end of the google fonts url string and it will not display the icon text for a longer time while the font loads. This may hurt traditional performance metrics. This can be augmented with a `<link rel="preload" href="<fonturl>">` so that the browser does not have to wait for a character to render to start fetching the font.

If that doesn't work you can hide visibility using the `document.fonts` `loadingdone` event. [Example.](https://lit.dev/playground/#gist=46dfc1b0b75d02eb0e1c07ada70d1555) [or the `ready` promise](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready).

[More info on the font loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API).

**Closed by e111077** 2023-07-28 21:34 UTC
