### ISSUE TITLE
md-list needs min-width

### ISSUE THREAD

**Issue by jonasherbert** [material-components/material-web#4928] opened 2023-09-14 09:55 UTC
Hi,
in pre17 display flex was added to md-list. Now I have to set a min-width for my lists to fill parent containers.

**Comment by e111077** [comment] 2023-09-17 21:54
this issue was brought up by a contributor as well. He's working on setting `display: block` on host since `<md-list>` is mimicking `<ul>` and `<ol>` which have `display:block` by the user agent

**Comment by asyncLiz** [comment] 2023-09-25 20:07
We use flexbox over block and inline due to bugs that are fixed by using flexbox, such as line-height sometimes adding extra vertical space.

List and list item have a default min width equal to the minimum width of their content. You can add `width: 100%` on `<md-list>` to make it fill its parent container.

If you're still running into problems, please post a reproduction with the parent container CSS that isn't working!

**Closed by asyncLiz** 2023-09-25 20:07 UTC
