### ISSUE TITLE
typing ENTER in a mwc-textfield inside a mwc-dialog invokes the @click handler on the primaryAction button

### ISSUE THREAD

**Issue by Jeffery25** [material-components/material-web#5284] opened 2023-12-13 15:57 UTC
### What is affected?

Component

### Description

The subject says it all: typing ENTER in a mwc-textfield inside a mwc-dialog makes the primaryAction button click (even when it's disabled).

Similar and maybe related to [this issue](https://github.com/material-components/material-web/issues/629).

### Reproduction

I am able to reproduce the bug with the following code (using the Lit framework):
```
<mwc-dialog>
  <mwc-textfield> </mwc-textfield>
  <mwc-button
    slot="primaryAction"
    @click="${() => console.log('You PRESSED THE BUTTON?!')}"
    .disabled="${true}">
    Do not press
  </mwc-button>
</mwc-dialog>
```
Clicking into the textfield and pressing enter will activate the button click event (even though it's disabled !)

### Workaround

No workarounds that I'm aware of.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Version 2.0

### Browser/OS/Node environment

Chrome

**Comment by asyncLiz** [comment] 2023-12-13 18:47
Think this is a duplicate of #629. [This comment](https://github.com/material-components/material-web/issues/629#issuecomment-582661585) provides the workaround, which is to stop the propagation of the enter keypress on the text field.

Closing since we're currently focused on the current `<md-*>` components instead of the older beta `<mwc-*>` ones.

**Closed by asyncLiz** 2023-12-13 18:47 UTC
