### ISSUE TITLE
Material 3 Data Tables

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-web#3867] opened 2023-01-02 11:57 UTC
Material 2 has data tables, which are implemented in [material-components-web](https://github.com/material-components/material-components-web/tree/master/packages/mdc-data-table). Will Material 3 and material-web have this component too? It's an essential item for my app environment - enterprise stuff.

**Comment by asyncLiz** [comment] 2023-01-03 17:41
Going to close as a dupe of https://github.com/material-components/material-web/issues/386, but yes, the plan is to implement the data table component for the Material 3 set.

**Closed by asyncLiz** 2023-01-03 17:41 UTC

**Comment by simonziegler** [comment] 2023-01-03 17:51
Phew. That was going to be awkward if not! Thanks @asyncLiz

**Comment by maicol07** [comment] 2023-01-15 14:23
In the meantime (waiting for the official component), I've implemented a M3 table webcomponent, combining the old MDC Table and M3 tokens. You can try it here: [Data Table - Docs](https://main--625eadb22bf40d003a32215a.chromatic.com/?path=/docs/data-table--docs) ([Github repo](https://github.com/maicol07/material-web-additions))
