### ISSUE TITLE
Dialog fails to close on "ESC" press

### ISSUE THREAD

**Issue by md5login** [material-components/material-web#5400] opened 2024-01-19 17:43 UTC
### What is affected?

Component

### Description

Create and show a "md-dialog" component. Press "esc". 
The backdrop remains on the screen. No close event is fired.

### Reproduction

[See here](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuICBcbiAgPHN0eWxlPlxuICAgIDpyb290IHtcbiAgICAgIGZvbnQtZmFtaWx5OiAnUm9ib3RvJywgc3lzdGVtLXVpLCBzYW5zLXNlcmlmO1xuICAgIH1cbiAgICBcbiAgICBsYWJlbCB7XG4gICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICB9XG4gIDwvc3R5bGU-XG48L2hlYWQ-XG48Ym9keT5cbiAgPG1kLWRpYWxvZyBvcGVuPlxuICAgIDxkaXYgc2xvdD1cImhlYWRsaW5lXCI-UFJFU1MgXCJFU0NcIjwvZGl2PlxuICAgIDxmb3JtIHNsb3Q9XCJjb250ZW50XCIgbWV0aG9kPVwiZGlhbG9nXCI-PC9mb3JtPlxuICAgIDxkaXYgc2xvdD1cImFjdGlvbnNcIj48L2Rpdj5cbiAgPC9tZC1kaWFsb2c-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoiaW5kZXguanMiLCJjb250ZW50IjoiaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL2RpYWxvZy9kaWFsb2cuanMnO1xuIn1d)

### Workaround

Didn't find a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 1.1.1

### Browser/OS/Node environment

Browser: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Node/NPM version irrelevant.

**Comment by asyncLiz** [comment] 2024-01-19 18:24
This is a duplicate of https://github.com/material-components/material-web/issues/5313, and https://github.com/material-components/material-web/issues/5384 is related. Try updating to `@material/web@nightly` to get the basic fix!

We'll have another release by the end of this month if you can't use nightly.

**Closed by asyncLiz** 2024-01-19 18:24 UTC
