### ISSUE TITLE
[mwc-textfield] - Outlined mwc-textfield label not visible if set while textfield is hidden

### ISSUE THREAD

**Issue by dejan9393** [material-components/material-web#2915] opened 2021-11-09 23:53 UTC
**Describe the bug**
When using an `outlined` `@material/mwc-textfield`, the `label` is not shown in the floating space in the textfield's border.

Here is a gif of the issue in action:
![9daf76d247346a0196ad70fe12627754](https://user-images.githubusercontent.com/13180986/141024246-1bf139fa-af05-471b-98ea-e501eca8c072.gif)

and here is a live reproduction with source code included:
https://mwc-textfield-label-bug.glitch.me/

Tested on Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

Edit: I've found a workaround; there exists a `layout()` method that we can call to recalculate the width of the label and the notch in the outline, however, I feel that there should be a mechanism for this to not have to be called manually by the user. Any ideas?

**Comment by dejan9393** [comment] 2021-11-09 23:54
Possibly related to #2840

**Comment by asyncLiz** [comment] 2021-11-12 19:59
Thanks! This is a duplicate of #2332 and #2166, this issue will be fixed in the new text field refactoring

**Closed by asyncLiz** 2021-11-12 19:59 UTC
Labels: Type: Bug, Focus Area: Components
