### ISSUE TITLE
Found 3 elements with non-unique id #button

### ISSUE THREAD

**Issue by isaacwein** [material-components/material-web#5344] opened 2023-12-25 05:34 UTC
### What is affected?

Component

### Description

if i have more then 1 button in a form with a type button on it, (to provent it from submiting the form)  the browser will throw an error with Found 3 elements with non-unique id #button

````html
<form action="null">
      <md-outlined-text-field label="Password" type="password">
        <md-icon-button toggle type="button" slot="trailing-icon">
          <md-icon>visibility</md-icon>
          <md-icon slot="selected">visibility_off</md-icon>
        </md-icon-button>
      </md-outlined-text-field>

      <br /><br /><br />
      <md-outlined-text-field label="Password" type="password">
        <md-icon-button toggle type="button" slot="trailing-icon">
          <md-icon>visibility</md-icon>
          <md-icon slot="selected">visibility_off</md-icon>
        </md-icon-button>
      </md-outlined-text-field>
      <br /><br /><br />
      <md-outlined-button type="sbmit">Submit</md-outlined-button>
    </form>
````

### Reproduction

Stsckblitz example https://stackblitz.com/edit/vitejs-vite-xdsjbm?file=index.html

### Workaround

I havent found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

version 1.1.1

### Browser/OS/Node environment

chrome browser version 120 on windows 11

**Comment by asyncLiz** [comment] 2023-12-25 20:47
This looks similar to https://github.com/material-components/material-web/issues/5213.

Are you using any tools or plugins to remove the shadow dom? The IDs are unique within each shadow root.

**Comment by datvm** [comment] 2023-12-27 21:59
@asyncLiz I believe Microsoft Edge DevTools report this no matter what (in the new Issues tab, not sure if Chrome has it too). This is a bug on DevTools, not MWC's.

![image](https://github.com/material-components/material-web/assets/6388546/e209e230-6575-4022-9c4f-80fe5e26b068)

Generally I find the info on that tab unhelpful than helpful.

**Comment by austinw-fineart** [comment] 2024-01-02 09:05
Can confirm as well, and OP's reproduction is sufficient:
[Playground link](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9idXR0b24vb3V0bGluZWQtYnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2ljb25idXR0b24vaWNvbi1idXR0b24uanNcIjtcbmltcG9ydCBcIkBtYXRlcmlhbC93ZWIvdGV4dGZpZWxkL291dGxpbmVkLXRleHQtZmllbGQuanNcIjsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGZvcm0-XG48bWQtb3V0bGluZWQtdGV4dC1maWVsZD48L21kLW91dGxpbmVkLXRleHQtZmllbGQ-XG48bWQtb3V0bGluZWQtdGV4dC1maWVsZCB0eXBlPVwicGFzc3dvcmRcIj48L21kLW91dGxpbmVkLXRleHQtZmllbGQ-XG48bWQtb3V0bGluZWQtYnV0dG9uPkEgbWF0ZXJpYWwgYnV0dG9uPC9tZC1vdXRsaW5lZC1idXR0b24-XG48bWQtb3V0bGluZWQtYnV0dG9uPkEgbWF0ZXJpYWwgYnV0dG9uPC9tZC1vdXRsaW5lZC1idXR0b24-XG48L2Zvcm0-XG48c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL21hdGVyaWFsLWltcG9ydHMuanNcIj48L3NjcmlwdD4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

However it appears to be a Chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1496312

**Comment by asyncLiz** [comment] 2024-01-08 19:33
Closing since this is a dev tools bug

**Closed by asyncLiz** 2024-01-08 19:33 UTC
