### ISSUE TITLE
Textarea can't be resized on Safari

### ISSUE THREAD

**Issue by litemerafrukt** [material-components/material-web#5449] opened 2024-02-08 08:39 UTC
### What is affected?

Component

### Description

Textareas cant be resized in Safari. I have tried with Safari 17.1 and Material web 1.2.0.

Could be a padding issue, seems a native textarea with padding >6px won't resize when I try in Safari.

### Reproduction

Try to resize [Textarea](https://material-web.dev/components/text-field/#textarea) in Safari.

### Workaround

I have not found a workaround besides using standard textarea.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Tried in 1.2.0

### Browser/OS/Node environment

Browser: 17.1
Mac OS: 14.1 (Sonoma)

**Comment by asyncLiz** [comment] 2024-02-08 18:39
Hm, yea I was able to reproduce on Safari with a jsbin `<textarea style="padding: 16px">`.

Can you [file a Safari bug](https://bugs.webkit.org/) and link it here?

**Comment by litemerafrukt** [comment] 2024-02-13 07:40
Seems the Safari padding bug is reported and worked on: [textarea resize doesn't work on Safari if it has 1rem padding]( https://bugs.webkit.org/show_bug.cgi?id=238193)

**Comment by asyncLiz** [comment] 2024-02-13 18:51
Great! I'll close this issue since we shouldn't need to do anything once it's fixed in webkit.

**Closed by asyncLiz** 2024-02-13 18:51 UTC
