### ISSUE TITLE
Extensionless imports in master-branch no longer supported by node-resolve 

### ISSUE THREAD

**Issue by kmmbvnr** [material-components/material-web#3548] opened 2022-08-03 04:23 UTC
Hi Team!

I've tried to get working the latest master version of the material-web, and got a lot of errors like:

```
Missing "./decorators" export in "lit" package

    material-web/textfield/outlined-text-field.ts:10:28:
      10 │ import {customElement} from 'lit/decorators';
```

It seems node-resole no longer allows to import without file extension, and all imprts should be changed to `import {customElement} from 'lit/decorators.js'`

https://github.com/rollup/plugins/issues/684#issuecomment-770517359

**Comment by kmmbvnr** [comment] 2022-08-20 04:55
It seems the same  problem as
https://github.com/material-components/material-web/issues/3395

It was fixed at https://github.com/material-components/material-web/commit/d99e3055e75d01f59c96098977e3450d0d3e7e5e

But appears again in the master branch with Material 3 refactor

cc @asyncLiz

**Comment by asyncLiz** [comment] 2022-08-24 17:59
Thanks for the issue! This is a dupe of #2632 but will be fixed shortly with https://github.com/material-components/material-web/pull/3623 :)

**Closed by asyncLiz** 2022-08-24 17:59 UTC
