### ISSUE TITLE
When v3 will be released for web

### ISSUE THREAD

**Issue by bielas** [material-components/material-web#3868] opened 2023-01-02 13:04 UTC
Are there any plans/date when v3 will be released?

**Comment by tajalaoui** [comment] 2023-01-02 16:13
The planned release was late 2022 as said in this reply: https://github.com/material-components/material-web/issues/3050#issuecomment-1011447013

**Comment by omar2205** [comment] 2023-01-02 23:15
There is an alpha already published https://www.npmjs.com/package/@material/web

**Comment by huangguacucumber** [comment] 2023-01-03 00:55
When will release v1 come?

**Comment by asyncLiz** [comment] 2023-01-03 17:33
> The planned release was late 2022 as said in this comment: [#3050 (comment)](https://github.com/material-components/material-web/issues/3050#issuecomment-1011447013)

It was, but some internal priorities were shifted around to meet that deadline, and this project now has fewer requirements and a different timeline for a v1 release.

It's just after the holidays, so expect a bit of a slower response, but a roadmap to v1 is on our list of todos 😊

**Comment by asyncLiz** [comment] 2023-01-03 17:37
Closing as a duplicate of https://github.com/material-components/material-web/issues/3050

**Closed by asyncLiz** 2023-01-03 17:37 UTC
