### ISSUE TITLE
Weird dialog behavior

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4756] opened 2023-08-20 19:56 UTC
https://github.com/material-components/material-web/assets/8685280/adb05cbd-d5f0-4bff-b3d8-c3f2d0461d4b

# Quick explainer
In the video you see the first dialog doesn't register the button click, it "clicks" the scrim but when pressing enter the button does register!

Second one works as expected registers button click and shows a pointer as cursor

`note that the working one is without the focus`

**Comment by VandeurenGlenn** [comment] 2023-08-23 19:51
Also encountered that dialog listens to the mouse out event (understandable) but should add a way to prevent it closes when selecting text like in an input field
Probably best to check if the click started in the dialog



https://github.com/material-components/material-web/assets/8685280/6dc60f26-4387-47cc-801b-9b3298cc86ed

**Comment by asyncLiz** [comment] 2023-09-11 19:57
For OP https://github.com/material-components/material-web/issues/4756#issue-1858248455, I'm not able to reproduce that. Can you provide a reproduction or the html/js you're using for the dialog?

For https://github.com/material-components/material-web/issues/4756#issuecomment-1688665859 #1, I'm not sure how we'd go about that, since a parent can't know about the size of its absolutely positioned children. You'll always need an explicit height and width on the parent. 

If you have something else in mind, can you provide an example with the browser `<dialog>` element of what you're looking for?

For https://github.com/material-components/material-web/issues/4756#issuecomment-1688665859 #2, what styles do you have on your content? It looks like it's setting `width: 100%`, which shouldn't be needed. I agree with your points on padding vs margin though, I'll see if I can make that swap.

For https://github.com/material-components/material-web/issues/4756#issuecomment-1690548111 I filed https://github.com/material-components/material-web/issues/4894

**Comment by asyncLiz** [comment] 2023-09-11 22:09
Swapped to padding in https://github.com/material-components/material-web/pull/4896

**Comment by VandeurenGlenn** [comment] 2023-09-12 19:52
"For OP https://github.com/material-components/material-web/issues/4756#issue-1858248455" 
I can't reproduce except in that one use case, it's a weird one, it works in allot of other projects and they are all setup the same but with [easy-home](https://github.com/VandeurenGlenn/peace-ui) its a problem, so for now just added all in shell instead of the imported views (when selected)

https://github.com/material-components/material-web/issues/4756#issuecomment-1688665859 https://github.com/material-components/material-web/issues/1
I don't  have a better solution that would "fix" one would think flex-box would fix it but it doesn't, I hoped you would know some hack

https://github.com/material-components/material-web/issues/4756#issuecomment-1688665859 https://github.com/material-components/material-web/pull/2
In some cases setting the width is needed
When using like list-item without list you would need to set the width to 100% else it wouldn't take the whole space

**Comment by asyncLiz** [comment] 2023-09-14 02:07
> I don't have a better solution that would "fix" one would think flex-box would fix it but it doesn't, I hoped you would know some hack

You could have the first "pane" of content be real content with `position: relative` to get the width and height, then use CSS to slider/layer other absolutely positioned child panes. That requires them all to be the same size, though.

You can also programmatically update the width/height of the dialog when it opens based on the size of one of the absolutely positioned panes.

> In some cases setting the width is needed
When using like list-item without list you would need to set the width to 100% else it wouldn't take the whole space

I don't think I'm able to reproduce that problem https://lit.dev/playground/#gist=be36f7c9190534c0fe0f7838f934bdc1

Setting width on a content child to `100%` should make it stretch to the `slot="content"` element.

> "For OP https://github.com/material-components/material-web/issues/4756#issue-1858248455"
I can't reproduce

I'm going to close this issue since there isn't much actionable right now, but feel free to keep the discussion going!

**Closed by asyncLiz** 2023-09-14 02:07 UTC

**Comment by VandeurenGlenn** [comment] 2023-09-16 18:01
> You could have the first "pane" of content be real content with `position: relative` to get the width and height, then use CSS to slider/layer other absolutely positioned child panes. That requires them all to be the same size, though.

Thanks @asyncLiz That gave me an idea
