### ISSUE TITLE
mwc-select gives accessibility error in Chrome Devtools audit

### ISSUE THREAD

**Issue by peterawlings** [material-components/material-web#1986] opened 2020-12-01 01:32 UTC
**Describe the bug**
Chrome Devtools accessibility audit gives an error:

`Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children.`

**To Reproduce**

1. Open select demo
2. run accessibility audit in chrome

**Expected behavior**
No audit errors

**Comment by e111077** [comment] 2020-12-01 19:10
Hello, we've talked at length with the accessibility team at google, chrome, and with the standards working group and we have come to the conclusion that our implementation of select is correct and that this is an issue more with chrome.

We do have plans to improve this further in the future with updates to the standard

**Comment by peterawlings** [comment] 2020-12-01 23:54
Thanks. Would I be right in thinking this is really an issue with the Axe Accessibility Engine from Deque Systems as we see the issue flagged in Storybook using the A11y add-on too, and I believe this is the same system powering both?

If so, is that something that needs to changed/udpdated?

**Comment by e111077** [comment] 2020-12-02 00:31
As a matter of fact, this made me go through my email chains again. My apologies, I didn't remember the situation 100% correctly.

We ended up contacting these teams because of inconsistencies in the w3c guidance on role=button + aria-haspopup=listbox vs role=combobox and aria-haspopup.

In the end we agreed that role=combobox was _more_ correct and announced correctly etc. The issue is that `role=combobox` requires a a listbox that aria only selects via IDs via `aria-owns`. This query unfortunately cannot pierce shadow dom.

Though, through review, the internal teams deemed that this component will announce and interact _sufficiently_ on our supported screen readers + assistive devices, but not _perfectly_.

So technically, lighthouse is correct and we must fix this likely via spec changes (see Accessibility Object Model which is under active development) or via a refactoring of this element.

Will keep open but likely icebox for now

**Comment by e111077** [comment] 2020-12-02 00:34
If you would like a workaround to this, you will likely have to subclass this element and inject your list items into the shadow root of the element + add the aria-owns with an ID (must be dynamically generated if you want to support shady dom and IE a11y)

**Comment by asyncLiz** [comment] 2023-09-27 00:13
Fixed in 1.0

**Closed by asyncLiz** 2023-09-27 00:13 UTC
Labels: Type: Bug
