### ISSUE TITLE
Ripple does not disappear in icon-button if button is disabled

### ISSUE THREAD

**Issue by jvail** [material-components/material-web#1321] opened 2020-05-16 08:28 UTC
I have a widget with several icon buttons that get disabled if one of the buttons is clicked. In firefox the ripple stays visible after disabling the button and even stays visible after enabling the button again. This may lead to having all button rendered with a ripple. In chrome it works as I would expect it.

**To Reproduce**
Paste this e.g. into the <body> of the icon-button demo:
```js
<div id='example'></div>
<script type="module">
  import { html, render } from 'https://unpkg.com/lit-html?module';

  const el = document.getElementById('example');
  let disabled = false;
  const toggle = () => {
      disabled = !disabled;
      render(renderBtns(), el);
  };
  const renderBtns = () => {
    return html`<div>
      <mwc-icon-button icon="code" ?disabled=${disabled} @click=${toggle}> </mwc-icon-button>
      <mwc-icon-button icon="code" @click=${toggle}></mwc-icon-button>
    </div>`;
  };
  render(renderBtns(), el);
</script>
```
* click the 1st button
* click the 2nd button

**Expected behavior**
Ripple of first button disappears after clicking the second

**Screenshots**
![image](https://user-images.githubusercontent.com/6503378/82114756-ebfa7080-975e-11ea-99bf-eb0152c0559a.png)

**Browser Version**
 - OS: linux
 - Browser: firefox
 - Version: 76.0.1

**Comment by e111077** [comment] 2020-05-18 21:55
I am unable to reproduce this issue on FF 76 on OSX. Can you please check if this leads to the same issue on your machine and if not can you please edit the jsbin to make it reflect this issue?

https://jsbin.com/cejanojori/2/edit?html,output

**Comment by jvail** [comment] 2020-05-19 06:15
![Capture](https://user-images.githubusercontent.com/6503378/82290562-46dad480-99b8-11ea-9345-1a58d74d08c1.PNG)

I gave it try with firefox (76.0.1 on windows 7) as well. First I  clicked the left button and then the right button and then somewhere in the window to let the right button ripple disappear. The left button gets enabled again but has a ripple. I can give it a try on my linux later but I'd guess it is the same since I can reproduce it on windows as well.

**Comment by e111077** [comment] 2020-05-19 06:19
I've finally gotten access to a Windows machine and also been able to repro on FF on Windows 10. Thanks for the confirmation

**Comment by jvail** [comment] 2020-05-19 13:20
Thank you. Since severity is low it might take some time until someone looks into it. Do you have an idea for a workaround? I tried to set --mdc-icon-button-ripple-opacity: 0 but that did not make any difference.

**Comment by e111077** [comment] 2020-05-19 18:39
try `--mdc-ripple-color: transparent`

**Comment by jvail** [comment] 2020-05-20 02:50
Thanks, I gave it a try in the jsbin but --mdc-ripple-color: transparent does not seem to make a difference either.

**Comment by e111077** [comment] 2020-05-20 21:25
ah apologies, it seems this one has not been migrated to the latest ripple implementation. This one still uses `--mdc-theme-on-primary: transparent` Though on hover it still seems to show, but that should fix your specific use case

**Comment by jvail** [comment] 2020-05-21 05:44
It does work for the right btn but not for the left. It seems there is really an issue with ripple + disabled. It's ok, I think I can live with this problem in firefox until the issue can be fixed. Thank you.

**Comment by asyncLiz** [comment] 2023-04-25 17:53
Should be fixed in M3

**Closed by asyncLiz** 2023-04-25 17:53 UTC
Labels: Type: Bug, Component: Icon Button, Component: Ripple, Feedback Requested, Focus Area: Components, Severity: Low
