### ISSUE TITLE
Select, Menu, and other menu-related components causes Chrome and similar Chromium Browsers to crash (Chrome 121.0.6153.0 and above)

### ISSUE THREAD

**Issue by lozandier** [material-components/material-web#5227] opened 2023-11-29 00:18 UTC
### What is affected?

Component

### Description

More recent builds of Chromium Browser(s) immediately crash when interacting with menu-related Material Compoents 
https://github.com/material-components/material-web/assets/1223224/38687ad2-a895-4547-ba66-c4d9f1f3f5fb

Version of @material/web tested: 1.0.1

### Reproduction

Steps to reproduce:

1) Use Chrome version 121.0.6153.0 and above
2) Attempt to open a menu/pop-over Material component on a 

## Expected outcome
Menu opens

## Current unexpected behavior
Browser crashes

https://github.com/material-components/material-web/assets/1223224/79e5cc9a-b11e-436e-89ee-1e8ff82d931b

### Workaround

I have not found a workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Latest version of @material/web 

### Browser/OS/Node environment

Google Chrome
121.0.6153.0 (Official Build) canary (x86_64) 

Revision
a5c13a277c5fb54744df20f5422eec52a573e632-refs/branch-heads/6153@{#1}
OS

macOS Version 14.1.1 (Build 23B81)

**Comment by e111077** [comment] 2023-12-13 23:45
hmm i can't get it to repro on Chrome Beta which is 121 but I can get it to repro on Canary which is 122

**Comment by e111077** [comment] 2023-12-14 00:01
Narrowed it down to chrome canary running into issues running the open animation itself which uses the native Web Animations API. I can't seem to debug what's going on because it just _fails_ between starting it and it ending.  Will try to generate a minimal repro to file on Chromium

**Comment by e111077** [comment] 2023-12-14 01:07
It specifically is the surface height animation causing the crash, but I cannot make a minimal repro of the issue so far. Here's what I have so far:

https://lit.dev/playground/#gist=2efe56a4ba5e241dad3c7883509ebd48

Will have to continue investigation especially if this issue moves from Canary (122) into Beta (121)

**Comment by e111077** [comment] 2023-12-14 01:19
Honestly I think Canary has all sorts of other issues. See this is the surface element and it's inline `style=` which should be wrong here:

![image](https://github.com/material-components/material-web/assets/5981958/bdc299ed-16bc-4a44-8080-0526d9774cbe)

Yet the calculate styles are:

![image](https://github.com/material-components/material-web/assets/5981958/28407a2c-d0d3-4061-83e0-5b4eebbf3801)

This is how it should look in stable:

![image](https://github.com/material-components/material-web/assets/5981958/19517b1e-f7b0-46a2-b2a2-4b6e81d7e0e3)

**Comment by christophe-g** [comment] 2024-01-24 06:41
Chrome 121 landed on stable. 

Menu and select crash the browser. 

tested with @material/web/@nightly.

**Comment by christophe-g** [comment] 2024-01-24 06:48
Workaround for now: set `quick=true` for all menu and select components to avoid animation on open and close.

**Comment by asyncLiz** [comment] 2024-01-24 17:21
@christophe-g what version of Chrome and OS does it crash on?

Chrome 121.0.6167.85 on Mac OS 14.2.1 doesn't crash when I interact with the menus on https://material-web.dev/components/menu/stories/, nor does it crash with the latest version internally.

**Comment by christophe-g** [comment] 2024-01-24 17:34
@asyncLiz - it is kind of good news that not all 121 version  crash ; ) 

- Browser : Version 121.0.6167.85 (Official Build) (64-bit)
- OS: Linux Mint 21.2 Cinnamon

Result of clicking first button of https://material-web.dev/components/menu/stories/ : 

![image](https://github.com/material-components/material-web/assets/1168053/7b0000e7-be04-4efc-a5cd-0df47f812b6a)

Nothing in the console. 

Opening a menu from https://material-web.dev/components/menu/:

![image](https://github.com/material-components/material-web/assets/1168053/5d39f522-310c-4641-a013-87ccffdabc09)

**Comment by christophe-g** [comment] 2024-01-24 17:50
Doing some further tests on Lambdatest.com and failing to reproduce the crash: 
- Windows 11 Chrome Version 121.0.6167.8: ok
- Windows 10 Chrome Version 121.0.6167.8: ok
- MacOS Sonoma Chrome Version 121.0.6167.8: ok

**Comment by asyncLiz** [comment] 2024-01-24 18:03
Chrome 121.0.6167.85 works on my corp Linux station. Are you able to test other Linux distros?

You may also check if chrome://flags/ has experimental web features enabled. If so, try disabling that flag, restarting, and see if it still crashes.

**Comment by christophe-g** [comment] 2024-01-24 18:08
>  chrome://flags/ has experimental web features enabled.

Oh - I would never have thought about this. You found the culprit !

Restarted without flag, WAI. Thank you.

**Comment by asyncLiz** [comment] 2024-01-24 18:20
This is an important bug to file in chromium, I believe they're working on popover stuff right now.

@e111077 pinging this on your radar since I think you're looking at some popover anchor stuff rn

**Comment by Darrenbydesign** [comment] 2024-09-03 17:15
I ran across a VERY similar issue and I thought I narrowed it down to any Custom Element that I had that was still set to `display: inline` would crash upon inspection of the element in the browser. This was also true for slotted elements like <a> tags (default inline). I wonder if they are related @asyncLiz

**Comment by asyncLiz** [comment] 2024-09-03 17:30
Chrome 121 is a bit old now, is this still happening on the latest versions of Chromium @Darrenbydesign?

**Comment by Darrenbydesign** [comment] 2024-09-07 02:55
> Chrome 121 is a bit old now, is this still happening on the latest versions of Chromium @Darrenbydesign?

I believe so Liz, as of yesterday on my with machine this issue still occurred. I've tried to report a bug about it but I'm not sure where to check on that status

**Closed** 2024-09-09 18:24 UTC
