### ISSUE TITLE
Request for cooperation from a beginner

### ISSUE THREAD

**Issue by MM25Zamanian** [material-components/material-web#3842] opened 2022-12-16 18:07 UTC
I am a beginner developer but I really want to work with your team (professionals).
It is possible to guide me and give me your small tasks

I met Lit almost a year ago and tried to learn it
Now I know lit to a certain extent
But I am still a beginner

**Comment by njfamirm** [comment] 2022-12-16 19:43
My mind has been busy contributing to this project for two days...
I shared this idea with my teammate; He is better than me; I am happy that we have made such a decision together 😌

I would like to contribute to this project for three reasons
1. Learning a lot while contributing!
2. Cooperation with a professional team!
3. **contribute to a great open-source project!**

I am a junior full-stack developer who focused more on the backend, But I have always loved making fast and light web apps
I have known Lit for about a year and we have done projects together with my teammate 💯 

**We look forward to working with your team!** ❤️ 

**Maybe we can start by making a demo and documentation; more considerable contributions are also a pleasure**

**Comment by asyncLiz** [comment] 2022-12-19 17:48
Thank you for your eagerness for contribution!

Unfortunately at the moment, we haven't set up a contribution guide (see https://github.com/material-components/material-web/issues/246), so we're not currently accepting many PRs for a while.

One way that you can absolutely help us early is by beta-testing the [`@material/web`](https://www.npmjs.com/package/@material/web) package and filing issues for bugs that you find (and we'll be doing a new release today! 😊)

Feel free to continue commenting, though for issue tracking I'm going to close this as a dupe of #246.

**Closed by asyncLiz** 2022-12-19 17:48 UTC

**Comment by njfamirm** [comment] 2022-12-19 19:16
Thank you for answering 💯

I am currently updating my site based on `@matrial/web`

Ok; I hope we can help you in the near future...
